name: graphics
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0=pyhd3eb1b0_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39h2bbff1b_0
  - asciitree=0.3.3=py_2
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py39haa95532_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bokeh=2.4.2=py39haa95532_1
  - bottleneck=1.3.4=py39h080aedc_0
  - brotli=1.0.9=ha925a31_2
  - brotlipy=0.7.0=py39h2bbff1b_1003
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2022.4.26=haa95532_0
  - cartopy=0.18.0=py39h80a4efb_1
  - certifi=2022.6.15=py39haa95532_0
  - cffi=1.15.0=py39h2bbff1b_1
  - cfitsio=3.470=h2bbff1b_7
  - cftime=1.5.1.1=py39h080aedc_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=7.1.2=pyhd3eb1b0_0
  - click-plugins=1.1.1=pyhd3eb1b0_0
  - cligj=0.7.2=py39haa95532_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - colorama=0.4.5=py39haa95532_0
  - colorcet=3.0.0=py39haa95532_0
  - cryptography=37.0.1=py39h21b164f_0
  - curl=7.82.0=h2bbff1b_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.11.0=py39h2bbff1b_0
  - dask=2022.5.0=py39haa95532_0
  - dask-core=2022.5.0=py39haa95532_0
  - datashader=0.13.0=pyhd3eb1b0_1
  - datashape=0.5.4=py39haa95532_1
  - debugpy=1.5.1=py39hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distributed=2022.5.0=py39haa95532_0
  - docopt=0.6.2=py39haa95532_0
  - entrypoints=0.4=py39haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.4=h6c2663c_0
  - fasteners=0.16.3=pyhd3eb1b0_0
  - fiona=1.8.13.post1=py39h758c064_0
  - flatbuffers=2.0.0=h6c2663c_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=hd328e21_0
  - freexl=1.0.6=h2bbff1b_0
  - fsspec=2022.3.0=py39haa95532_0
  - gdal=3.0.2=py39hb978731_2
  - geopandas=0.9.0=py_1
  - geopandas-base=0.9.0=py_1
  - geos=3.8.0=h33f27b4_0
  - geotiff=1.7.0=h4545760_0
  - geoviews-core=1.8.1=pyh06a4308_1
  - grpcio=1.42.0=py39hc60d5dd_0
  - h5py=3.6.0=py39h3de5c98_0
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.10.6=h1756f20_1
  - heapdict=1.0.1=pyhd3eb1b0_0
  - holoviews=1.14.7=pyhd3eb1b0_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - idna=3.3=pyhd3eb1b0_0
  - importlib-metadata=4.11.3=py39haa95532_0
  - intel-openmp=2021.4.0=haa95532_3556
  - ipykernel=6.9.1=py39haa95532_0
  - ipython=8.3.0=py39haa95532_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.1=py39haa95532_1
  - jinja2=3.0.3=pyhd3eb1b0_0
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=h2bbff1b_0
  - jsonschema=4.4.0=py39haa95532_0
  - jupyter_client=7.2.2=py39haa95532_0
  - jupyter_core=4.10.0=py39haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - kealib=1.4.14=hde4a422_1
  - kiwisolver=1.4.2=py39hd77b12b_0
  - libcurl=7.82.0=h86230a5_0
  - libgdal=3.0.2=h3d7c30d_2
  - libiconv=1.16=h2bbff1b_2
  - libnetcdf=4.8.1=h6685c40_1
  - libpng=1.6.37=h2a8f88b_0
  - libpq=12.9=hb652d5d_3
  - libprotobuf=3.20.1=h23ce68f_0
  - libspatialindex=1.9.3=h6c2663c_0
  - libspatialite=4.3.0a=h14feca5_20
  - libssh2=1.10.0=hcd4344a_0
  - libtiff=4.2.0=he0120a3_1
  - libwebp=1.2.2=h2bbff1b_0
  - libxml2=2.9.14=h0ad7f3c_0
  - libzip=1.8.0=h49b8836_0
  - llvmlite=0.36.0=py39h34b8924_4
  - locket=1.0.0=py39haa95532_0
  - lz4=3.1.3=py39h2bbff1b_0
  - lz4-c=1.9.3=h2bbff1b_1
  - m2w64-expat=2.1.1=2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gettext=0.19.7=2
  - m2w64-gmp=6.1.0=2
  - m2w64-libiconv=1.14=6
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-xz=5.2.2=2
  - mapclassify=2.4.3=pyhd3eb1b0_0
  - markdown=3.3.4=py39haa95532_0
  - markupsafe=2.1.1=py39h2bbff1b_0
  - matplotlib=3.5.1=py39haa95532_1
  - matplotlib-base=3.5.1=py39hd77b12b_1
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py39h2bbff1b_1000
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py39h2bbff1b_0
  - mkl_fft=1.3.1=py39h277e83a_0
  - mkl_random=1.2.2=py39hf11a4ad_0
  - msgpack-python=1.0.3=py39h59b6b97_0
  - msys2-conda-epoch=20160418=1
  - multipledispatch=0.6.0=py39haa95532_0
  - munch=2.5.0=pyhd3eb1b0_0
  - munkres=1.1.4=py_0
  - nbclient=0.5.13=py39haa95532_0
  - nbconvert=6.4.4=py39haa95532_0
  - nbformat=5.3.0=py39haa95532_0
  - nest-asyncio=1.5.5=py39haa95532_0
  - netcdf4=1.5.7=py39h3de5c98_1
  - networkx=2.7.1=pyhd3eb1b0_0
  - notebook=6.4.11=py39haa95532_0
  - numba=0.53.1=py39hf11a4ad_0
  - numcodecs=0.8.0=py39hd77b12b_0
  - numexpr=2.8.3=py39hb80d3ca_0
  - numpy=1.22.3=py39h7a0a035_0
  - numpy-base=1.22.3=py39hca35cd5_0
  - openjpeg=2.4.0=h4fc8c34_0
  - openssl=1.1.1p=h2bbff1b_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.2=py39hd77b12b_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - panel=0.13.0=py39haa95532_0
  - param=1.12.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_1
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.0.1=py39hdc2b20a_0
  - pip=21.2.4=py39haa95532_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - proj=6.2.1=h3758d61_0
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - protobuf=3.20.1=py39hd77b12b_0
  - pseudonetcdf=3.2.2=pyhd8ed1ab_0
  - psutil=5.9.0=py39h2bbff1b_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyct=0.4.6=py39haa95532_0
  - pydap=3.3.0=pyhd8ed1ab_0
  - pyepsg=0.4.0=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyproj=2.6.1.post1=py39h593ac45_1
  - pyqt=5.9.2=py39hd77b12b_6
  - pyreadline=2.1=py39haa95532_1
  - pyrsistent=0.18.0=py39h196d8e1_0
  - pyshp=2.1.3=pyhd3eb1b0_0
  - pysocks=1.7.1=py39haa95532_0
  - python=3.9.12=h6244533_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.15.1=pyhd3eb1b0_0
  - pytz=2022.1=py39haa95532_0
  - pyviz_comms=2.0.2=pyhd3eb1b0_0
  - pywin32=302=py39h2bbff1b_2
  - pywinpty=2.0.2=py39h5da7b33_0
  - pyyaml=6.0=py39h2bbff1b_1
  - pyzmq=22.3.0=py39hd77b12b_2
  - qt=5.9.7=vc14h73c81de_0
  - rasterio=1.2.10=py39h17c1fa0_0
  - requests=2.28.0=py39haa95532_0
  - rtree=0.9.7=py39h2eaa2aa_1
  - scikit-learn=1.0.2=py39hf11a4ad_1
  - scipy=1.7.3=py39h0a974cb_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=61.2.0=py39haa95532_0
  - shapely=1.7.1=py39h06580b3_0
  - sip=4.19.13=py39hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - snuggs=1.4.7=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sqlite=3.38.5=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2020.3=h74a9793_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - terminado=0.13.1=py39haa95532_0
  - testpath=0.6.0=py39haa95532_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tiledb=2.3.3=h3649cd2_2
  - tk=8.6.12=h2bbff1b_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - tornado=6.1=py39h2bbff1b_0
  - tqdm=4.64.0=py39haa95532_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing-extensions=4.1.1=hd3eb1b0_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - tzdata=2022a=hda174b7_0
  - urllib3=1.26.9=py39haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39haa95532_1
  - webob=1.8.7=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=py39haa95532_0
  - wincertstore=0.2=py39haa95532_2
  - winpty=0.4.3=4
  - xarray=0.20.1=pyhd3eb1b0_1
  - xerces-c=3.2.3=ha925a31_0
  - xz=5.2.5=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - zarr=2.8.1=pyhd3eb1b0_0
  - zict=2.1.0=py39haa95532_0
  - zipp=3.8.0=py39haa95532_0
  - zlib=1.2.12=h8cc25b3_2
  - zstd=1.5.2=h19a0ad4_0
  - pip:
    - cython==0.29.30
    - deprecated==1.2.13
    - geoviews==1.9.4
    - gpy==1.10.0
    - hvplot==0.8.0
    - openeo==0.11.0
    - paramz==0.9.5
    - vam-whittaker==2.0.2
    - wrapt==1.14.1
prefix: C:\Users\DRIESSEB\.conda\envs\graphics
